### ISSUE TITLE
Estimator usage

### ISSUE THREAD

**Issue by rhyspang** [MrGemy95/Tensorflow-Project-Template#23]
what is the appropriate way to use estimator in the template?

**Comment by sidshopin** [comment]
I think estimator solves a lot of the boilerplate issues for you (summary writing, train, eval loops etc). Since this Project Template was ahead of TF Estimator, they both solve similar issues.  So its either Estimator or this project template. 

Estimator claims to have native support for distributed training though. Not sure what that means yet.

**Comment by switchfootsid** [comment]
I think TF Estimator solves a lot of the boilerplate issues for you just like this repo (summary writing, train, eval loops etc). Since this Project Template was ahead of TF Estimator, they both solve similar issues. So its either Estimator or this project template.

Estimator claims to have native support for distributed training though. Not sure what that means yet.

**Comment by mgsalem** [comment]
to use estimators you can change the trainer to not to inherit the trainer_base, and in the new trainer you can create the estimator spec connect the model and the data_loader into Estimator class.
